# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 265)
        MainWindow.setMinimumSize(QtCore.QSize(400, 150))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.caixa27 = QtWidgets.QLabel(self.centralwidget)
        self.caixa27.setGeometry(QtCore.QRect(310, 10, 91, 91))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.caixa27.setFont(font)
        self.caixa27.setObjectName("caixa27")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 241, 111))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Hebrew")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 130, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Hebrew")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.dvr = QtWidgets.QLabel(self.centralwidget)
        self.dvr.setGeometry(QtCore.QRect(320, 140, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.dvr.setFont(font)
        self.dvr.setObjectName("dvr")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Programa Titulo"))
        self.caixa27.setText(_translate("MainWindow", "x"))
        self.label_2.setText(_translate("MainWindow", "CAIXA 27"))
        self.label_13.setText(_translate("MainWindow", "DVR"))
        self.dvr.setText(_translate("MainWindow", "x"))
